/*****************************************************************
 ** @author   STF 470
 ** @version  0.0.1
 ** @purpose  1:22.4, Verify behaviour of port.check(getreply) in case of unsuccessful match in standalone statement
 ** @verdict  pass accept, ttcn3verdict:pass
 *****************************************************************/
module Sem_2204_the_check_operation_059 {

	signature S(out integer p_par1) return integer;
	type port P procedure {
		inout S;
	}

    type component GeneralComp {
		port P p;
	}

	function f() runs on GeneralComp {
		p.getcall;
		setverdict(pass, "Call received");
		p.reply(S:{ p_par1 := 1} value 5);
	}

	altstep a() runs on GeneralComp {
		[] p.getreply {
			setverdict(pass, "As expected, the check operation didn't match");
			stop;
		}
	}

	testcase TC_Sem_2204_the_check_operation_059() runs on GeneralComp system GeneralComp{
		var GeneralComp v_ptc := GeneralComp.create;
		activate(a());
		connect(self:p, v_ptc:p);
		p.call(S:{ p_par1 := - }, nowait);
		v_ptc.start(f());
        p.check(getreply(S:? value ?) from self);
		setverdict(fail, "Incorrect match");
    }

    control {
        execute(TC_Sem_2204_the_check_operation_059(), 5.0);
    }
}