/*****************************************************************
 ** @author   STF 470
 ** @version  0.0.1
 ** @purpose  1:22.4, Verify behaviour of port.check(getcall) in case of unsuccessful match in standalone statement
 ** @verdict  pass accept, ttcn3verdict:pass
 *****************************************************************/
module Sem_2204_the_check_operation_035 {

	signature S(integer p_par1);
	type port P procedure {
		inout S;
	}

    type component GeneralComp {
		port P p;
	}

	altstep a() runs on GeneralComp {
		[] p.getcall {
			setverdict(pass, "As expected, the check operation didn't match");
			stop;
		}
	}

	function f() runs on GeneralComp {
		activate(a());
        p.check(getcall(S:{ p_par1 := (0, 2, 4, 6)}));
		setverdict(fail, "Incorrect match");
	}

	testcase TC_Sem_2204_the_check_operation_035() runs on GeneralComp system GeneralComp{
		var GeneralComp v_ptc := GeneralComp.create;
		connect(self:p, v_ptc:p);
		p.call(S:{ p_par1 := 1 }, nowait);
		v_ptc.start(f());
		v_ptc.done;
    }

    control {
        execute(TC_Sem_2204_the_check_operation_035(), 5.0);
    }
}